project:
  type: website

website:
  title: "My Website for emperical project"
  navbar:
    left:
      - href: blog_website.qmd
        text: Home
      - href: index.qmd
        text: Info
      - href: results.qmd
        text: Results
      - href: conclusion.qmd
        text: Conclusion
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true