project:
  type: website

website:
  title: "My Quarto Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog_website.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
